language:
  - python
  - node_js

# Make sure the plugin works in the two most recent python versions
python:
  - "2.7"
  - "3.3"

install:
  - npm install -g grunt-cli
  - npm run-script devsetup
  - npm install

script:
  # Make sure that the postinstall script has run correctly
  - test -d tasks/lib/nose
  - grunt

  # Okay, seems to be good. Lets test that the installation procedure works as well
  # first, remove any artifacts
  - grunt clean
  - rm -rf tasks/lib/nose

  # Okay, now this is how the stuff should seem when it's downloaded from npm
  # Let's try to do a local install and check that it works
  - cp -r test/fixtures/exampleNewProject ../
  - cd ../exampleNewProject
  - npm install ../grunt-nose

  # that should have installed everything needed, lets test that!

  # test that local version of nose was installed
  - test -d node_modules/grunt-nose/tasks/lib/nose

  # test that a nose task can be run
  - grunt nose

  # test that it generated a result file
  - test -f nosetests.xml

  # ...and finally that the correct number of tests was run (and no failures)
  - grep tests=\"1\" nosetests.xml
  - grep errors=\"0\" nosetests.xml

notifications:
  email: false
